/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationidologis;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author denver
 */
public class Locations extends javax.swing.JFrame {
private Menu fen;
    /**
     * Creates new form Locations
     */

    
    bdd.Cobdd conn = new bdd.Cobdd();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model=new DefaultTableModel();
    
    
    public Locations() {
        this.setVisible(true);
        initComponents();
        
        
model.addColumn("id");   
model.addColumn("type");
model.addColumn("surface");
model.addColumn("terrain");
model.addColumn("chambres");
model.addColumn("loyer");
    


try{
    stm=conn.obtenirconnexion().createStatement();
    ResultSet Rs=stm.executeQuery("SELECT reference, type.libelle AS type, secteur.libelle AS secteur, surface, chambres, surface_terrain, classe_energetique, les_plus, loyer, img "
            + "FROM location "
            + "INNER JOIN type ON type.id = location.id_type "
            + "INNER JOIN secteur ON secteur.id = location.id_secteur");

    while(Rs.next()){
        model.addRow(new Object[]{Rs.getString("reference"),Rs.getString("type"),Rs.getString("surface"),
            Rs.getString("surface_terrain"),Rs.getString("chambres"),Rs.getString("loyer")});
        }
}
catch(Exception e)
{
    System.err.println(e);
}

tblLoca.setModel(model);

    
    



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSurface = new javax.swing.JTextField();
        txtSurTerrain = new javax.swing.JTextField();
        txtPlus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtLoyer = new javax.swing.JTextField();
        txtCE = new javax.swing.JTextField();
        txtChambres = new javax.swing.JTextField();
        comboType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        comboSecteur = new javax.swing.JComboBox<>();
        txtImg = new javax.swing.JTextField();
        jEnv = new javax.swing.JCheckBox();
        btnRetLoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoca = new javax.swing.JTable();
        btnAjouterL = new javax.swing.JButton();
        btnModifierL = new javax.swing.JButton();
        btnSupprL = new javax.swing.JButton();
        jFileLoca = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1411, 700));

        jLabel2.setText("type");

        jLabel8.setText("les_plus");

        jLabel7.setText("classe_energetique");

        jLabel6.setText("surface terrain");

        jLabel5.setText("chambres");

        jLabel3.setText("secteur");

        jLabel4.setText("surface");

        jLabel10.setText("Loyer ");

        txtLoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoyerActionPerformed(evt);
            }
        });

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Appartement", "Maison", "Pavillon" }));
        comboType.setSelectedIndex(1);

        jLabel9.setText("Image :");

        comboSecteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Calais", "Dunkerque", "Lille", "Paris", "Arras", " " }));
        comboSecteur.setSelectedIndex(1);

        txtImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImgActionPerformed(evt);
            }
        });

        jEnv.setText("Envoyer");
        jEnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSurface)
                            .addComponent(comboType, 0, 138, Short.MAX_VALUE)
                            .addComponent(comboSecteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtSurTerrain, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtChambres))
                        .addGap(550, 550, 550))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoyer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEnv))
                            .addComponent(txtPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtSurTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtChambres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtLoyer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnv))
                .addGap(24, 24, 24))
        );

        btnRetLoc.setBackground(new java.awt.Color(234, 212, 137));
        btnRetLoc.setText("RETOUR");
        btnRetLoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRetLoc.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnRetLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetLocActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 3, 24)); // NOI18N
        jLabel1.setText("GERER LES LOCATIONS");

        tblLoca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLoca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLocaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoca);

        btnAjouterL.setText("Ajouter");
        btnAjouterL.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnAjouterL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterLActionPerformed(evt);
            }
        });

        btnModifierL.setText("Modifier");
        btnModifierL.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnModifierL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierLActionPerformed(evt);
            }
        });

        btnSupprL.setText("Supprimer");
        btnSupprL.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnSupprL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprLActionPerformed(evt);
            }
        });

        jFileLoca.setCurrentDirectory(new java.io.File("/home/denver/NetBeansProjects/Appli_Idologis-master/src/applicationidologis/icone"));
        jFileLoca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFileLoca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileLocaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouterL, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnModifierL, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnSupprL, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRetLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jFileLoca, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFileLoca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouterL)
                            .addComponent(btnSupprL)
                            .addComponent(btnModifierL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void deplace(int i){
    try{
        comboType.setSelectedItem(model.getValueAt(i,0).toString());
        comboSecteur.setSelectedItem(model.getValueAt(i,1).toString());
        txtSurface.setText(model.getValueAt(i,2).toString());
        txtChambres.setText(model.getValueAt(i,3).toString());
        txtSurTerrain.setText(model.getValueAt(i,4).toString());
        txtCE.setText(model.getValueAt(i,5).toString());
        txtPlus.setText(model.getValueAt(i,6).toString());
        txtLoyer.setText(model.getValueAt(i,7).toString());
 

       

    }
    catch(Exception e){
        System.err.println(e);
        JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
    }
}


//FileFilter imagesFilter = new FileNameExtensionFilter("Images", "bmp", "gif", "jpg", "jpeg", "png", ...);


private void afficher(){
try{
    
        model.setRowCount(0);
    stm=conn.obtenirconnexion().createStatement();
    ResultSet Rs=stm.executeQuery("SELECT reference, type.libelle AS type, secteur.libelle AS secteur, surface, chambres, surface_terrain, classe_energetique, les_plus, loyer, img "
            + "FROM location "
            + "INNER JOIN type ON type.id = location.id_type "
            + "INNER JOIN secteur ON secteur.id = location.id_secteur");
    while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("reference"),Rs.getString("type"),Rs.getString("surface"),
            Rs.getString("surface_terrain"),Rs.getString("chambres"),Rs.getString("loyer")});
        }

}
catch(Exception e)
{
    System.err.println(e);
}

tblLoca.setModel(model);


}



    private void txtLoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoyerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoyerActionPerformed

    private void btnRetLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetLocActionPerformed
        // TODO add your handling code here:
        this.dispose();
        fen = new Menu();
    }//GEN-LAST:event_btnRetLocActionPerformed

    private void tblLocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLocaMouseClicked
        // TODO add your handling code here:

        String id;
        id = (String.valueOf(tblLoca.getValueAt(tblLoca.getSelectedRow(), 0)));
        try {
            Rs=stm.executeQuery("SELECT reference, type.libelle AS type, secteur.libelle AS secteur, surface, chambres, surface_terrain, classe_energetique, les_plus, loyer, img "
            + "FROM location "
            + "INNER JOIN type ON type.id = location.id_type "
            + "INNER JOIN secteur ON secteur.id = location.id_secteur "
            + "WHERE reference='"+id+"'");

            Rs.next();
            comboType.setSelectedItem(Rs.getString(2));
            comboSecteur.setSelectedItem(Rs.getString(3));
            txtSurface.setText(Rs.getString(4));
            txtChambres.setText(Rs.getString(5));
            txtSurTerrain.setText(Rs.getString(6));
            txtCE.setText(Rs.getString(7));
            txtPlus.setText(Rs.getString(8));
            txtLoyer.setText(Rs.getString(9));
            txtImg.setText(Rs.getString(10));

  

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"erreur de deplacement "+ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_tblLocaMouseClicked

    private void btnAjouterLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterLActionPerformed
        // TODO add your handling code here:

        Integer type = comboType.getSelectedIndex();
        Integer secteur = comboSecteur.getSelectedIndex();
        String surface = txtSurface.getText();
        String chambres = txtChambres.getText();
        String surface_terrain = txtSurTerrain.getText();
        String classe_energetique = txtCE.getText();
        String les_plus = txtPlus.getText();
        String loyer = txtLoyer.getText();
        String img = txtImg.getText();

        
        
        String requete="insert into location (id_type, id_secteur, surface, chambres, surface_terrain, classe_energetique, les_plus, loyer, img) VALUES ('"+type+"','"+secteur+"','"+surface+"','"+chambres+"','"+surface_terrain+"','"+classe_energetique+"','"+les_plus+"','"+loyer+"','"+img+"')";

        try {
            stm.executeUpdate(requete);
            JOptionPane.showMessageDialog(null,"Location ajouté");

            afficher();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }

    }//GEN-LAST:event_btnAjouterLActionPerformed

    private void btnModifierLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierLActionPerformed
        // TODO add your handling code here:

        String reference = null;
        reference = String.valueOf(tblLoca.getValueAt(tblLoca.getSelectedRow(), 0));

        try{
            if(JOptionPane.showConfirmDialog (null,"Confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {

            stm.executeUpdate("UPDATE location SET id_type='"+comboType.getSelectedIndex()+"',id_secteur='"+comboSecteur.getSelectedIndex()+
                "',surface='"+txtSurface.getText()+ "',chambres='"+txtChambres.getText()+"',surface_terrain='"+txtSurTerrain.getText()+
                "',classe_energetique='"+txtCE.getText()+"',les_plus='"+txtPlus.getText()+"',loyer='"+txtLoyer.getText()+"',img='"+txtImg.getText()+
                "' WHERE reference= "+reference);

            afficher();

        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"erreur modif ! "+e.getMessage());
            System.err.println(e);
        }

    }//GEN-LAST:event_btnModifierLActionPerformed

    private void btnSupprLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprLActionPerformed
        // TODO add your handling code here:

        try {

            String reference = null;
            reference = String.valueOf(tblLoca.getValueAt(tblLoca.getSelectedRow(), 0));

            if(JOptionPane.showConfirmDialog(null,"Etes vous sur de vouloir supprimer cette location "
                ,"supprimer location",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)

        if(reference.length() != 0) {
            stm.executeUpdate("Delete From location where reference="+reference); afficher();

        }
        else {
            JOptionPane.showMessageDialog(null,"veuillez selectionner une location !! ");

        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"erreur suppr \n"+e.getMessage());

        }

    }//GEN-LAST:event_btnSupprLActionPerformed

    private void txtImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgActionPerformed

    private void jFileLocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileLocaActionPerformed
        // TODO add your handling code here:

    txtImg.setText(jFileLoca.getSelectedFile().getName());
        
    }//GEN-LAST:event_jFileLocaActionPerformed

    private void jEnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnvActionPerformed
        // TODO add your handling code here:
              
        Path source = Paths.get(jFileLoca.getSelectedFile().getAbsolutePath());
        Path target = Paths.get("192.168.176.10/var/www/idologis/img/");
    try {
        Files.copy(source, target, REPLACE_EXISTING); 
    } catch (IOException ex) {
        Logger.getLogger(Locations.class.getName()).log(Level.SEVERE, null, ex);
    }

        
    }//GEN-LAST:event_jEnvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Locations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Locations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterL;
    private javax.swing.JButton btnModifierL;
    private javax.swing.JButton btnRetLoc;
    private javax.swing.JButton btnSupprL;
    private javax.swing.JComboBox<String> comboSecteur;
    public javax.swing.JComboBox<String> comboType;
    private javax.swing.JCheckBox jEnv;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileLoca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoca;
    private javax.swing.JTextField txtCE;
    private javax.swing.JTextField txtChambres;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtLoyer;
    private javax.swing.JTextField txtPlus;
    private javax.swing.JTextField txtSurTerrain;
    private javax.swing.JTextField txtSurface;
    // End of variables declaration//GEN-END:variables
}
