/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applicationidologis;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author denver
 */
public class Ventes extends javax.swing.JFrame {
    private Menu fen;

    /**
     * Creates new form Ventes
     */
    
    
    bdd.Cobdd conn = new bdd.Cobdd();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model=new DefaultTableModel();
    
    
    
    public Ventes() {
        this.setVisible(true);
        initComponents();
        
model.addColumn("id");   
model.addColumn("type");
model.addColumn("surface");
model.addColumn("terrain");
model.addColumn("chambres");
model.addColumn("prix");


try{
    stm=conn.obtenirconnexion().createStatement();
    ResultSet Rs=stm.executeQuery("SELECT reference, type.libelle AS type, secteur.libelle AS secteur, surface, chambres, surface_terrain, classe_energetique, prix, les_plus " +
	"FROM vente  "+
	"INNER JOIN type ON type.id = vente.id_type  "+
	"INNER JOIN secteur ON secteur.id = vente.id_secteur");
    while(Rs.next()){
        model.addRow(new Object[]{Rs.getString("reference"),Rs.getString("type"),Rs.getString("surface"),
            Rs.getString("surface_terrain"),Rs.getString("chambres"),Rs.getString("prix")});
        }
}
catch(Exception e)
{
    System.err.println(e);
}

tblVentes.setModel(model);

    
    




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


private void deplace(int i){
    try{
        comboType.setSelectedItem(model.getValueAt(i,0).toString());
        comboSecteur.setSelectedItem(model.getValueAt(i,1).toString());
        txtSurface.setText(model.getValueAt(i,2).toString());
        txtChambres.setText(model.getValueAt(i,3).toString());
        txtSurTerrain.setText(model.getValueAt(i,4).toString());
        txtCE.setText(model.getValueAt(i,5).toString());
        txtPlus.setText(model.getValueAt(i,6).toString());
        txtPrix.setText(model.getValueAt(i,7).toString());
 

       

    }
    catch(Exception e){
        System.err.println(e);
        JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());
    }
}



private void afficher(){
try{
    
        model.setRowCount(0);
    stm=conn.obtenirconnexion().createStatement();
    ResultSet Rs=stm.executeQuery("SELECT reference, type.libelle AS type, secteur.libelle AS secteur, surface, chambres, surface_terrain, classe_energetique, prix, les_plus " +
"	FROM vente " +
"	INNER JOIN type ON type.id = vente.id_type " +
"	INNER JOIN secteur ON secteur.id = vente.id_secteur");
    while(Rs.next()){
            model.addRow(new Object[]{Rs.getString("reference"),Rs.getString("type"),Rs.getString("surface"),
            Rs.getString("surface_terrain"),Rs.getString("chambres"),Rs.getString("prix")});
        }
}
catch(Exception e)
{
    System.err.println(e);
}

tblVentes.setModel(model);


}
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRetVentes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSurface = new javax.swing.JTextField();
        txtSurTerrain = new javax.swing.JTextField();
        txtPlus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrix = new javax.swing.JTextField();
        txtCE = new javax.swing.JTextField();
        txtChambres = new javax.swing.JTextField();
        comboType = new javax.swing.JComboBox<>();
        comboSecteur = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtImg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentes = new javax.swing.JTable();
        btnAjouterV = new javax.swing.JButton();
        btnModifierV = new javax.swing.JButton();
        btnSupprV = new javax.swing.JButton();
        jFileVente = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRetVentes.setBackground(new java.awt.Color(234, 212, 137));
        btnRetVentes.setText("RETOUR");
        btnRetVentes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRetVentes.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnRetVentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetVentesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 3, 24)); // NOI18N
        jLabel1.setText("GERER LES VENTES");

        jLabel2.setText("type");

        jLabel8.setText("les_plus");

        jLabel7.setText("classe_energetique");

        jLabel6.setText("surface terrain");

        jLabel5.setText("chambres");

        jLabel3.setText("secteur");

        jLabel4.setText("surface");

        jLabel10.setText("Prix : ");

        txtPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixActionPerformed(evt);
            }
        });

        comboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Appartement", "Maison", "Pavillon" }));
        comboType.setSelectedIndex(1);

        comboSecteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "Calais", "Dunkerque", "Lille", "Paris", "Arras", " " }));
        comboSecteur.setSelectedIndex(1);

        jLabel11.setText("Image :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboType, 0, 126, Short.MAX_VALUE)
                            .addComponent(txtSurface)
                            .addComponent(comboSecteur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSurTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCE)
                            .addComponent(txtChambres)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlus)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 30, Short.MAX_VALUE)))))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtSurTerrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSurface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtChambres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tblVentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVentes);

        btnAjouterV.setText("Ajouter");
        btnAjouterV.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnAjouterV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterVActionPerformed(evt);
            }
        });

        btnModifierV.setText("Modifier");
        btnModifierV.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnModifierV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierVActionPerformed(evt);
            }
        });

        btnSupprV.setText("Supprimer");
        btnSupprV.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnSupprV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprVActionPerformed(evt);
            }
        });

        jFileVente.setCurrentDirectory(new java.io.File("/home/denver/NetBeansProjects/Appli_Idologis-master/src/applicationidologis/icone"));
        jFileVente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileVenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRetVentes, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(btnAjouterV, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(94, 94, 94)
                            .addComponent(btnModifierV, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86)
                            .addComponent(btnSupprV, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jFileVente, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFileVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRetVentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouterV)
                            .addComponent(btnModifierV)
                            .addComponent(btnSupprV))
                        .addGap(49, 49, 49)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetVentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetVentesActionPerformed
        // TODO add your handling code here:
        this.dispose();
        fen = new Menu();
    }//GEN-LAST:event_btnRetVentesActionPerformed

    private void txtPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixActionPerformed

    private void btnAjouterVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterVActionPerformed
        // TODO add your handling code here:
        
        Integer type = comboType.getSelectedIndex();
        Integer secteur = comboSecteur.getSelectedIndex();
        String surface = txtSurface.getText();
        String chambres = txtChambres.getText();
        String surface_terrain = txtSurTerrain.getText();
        String classe_energetique = txtCE.getText();
        String les_plus = txtPlus.getText();
        String prix = txtPrix.getText();
        String img = txtImg.getText();

        
               
        String requete="insert into vente (id_type,id_secteur,surface,chambres,surface_terrain,classe_energetique,les_plus,prix,img) VALUES ('"+type+"','"+secteur+"','"+surface+"','"+chambres+"','"+surface_terrain+"','"+classe_energetique+"','"+les_plus+"','"+prix+"','"+img+"')";
        
        
            try {
                stm.executeUpdate(requete);
                JOptionPane.showMessageDialog(null,"Vente ajouté");

                afficher();
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null,ex.getMessage());
            }
       
        
    }//GEN-LAST:event_btnAjouterVActionPerformed

    private void tblVentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentesMouseClicked
        // TODO add your handling code here:
        
        String id;
        id = (String.valueOf(tblVentes.getValueAt(tblVentes.getSelectedRow(), 0)));
        try {
            Rs=stm.executeQuery("SELECT reference, type.libelle AS type, secteur.libelle AS secteur, surface, chambres, surface_terrain, classe_energetique, les_plus, prix " +
"	FROM vente " +
"	INNER JOIN type ON type.id = vente.id_type " +
"	INNER JOIN secteur ON secteur.id = vente.id_secteur" +
"       Where reference='"+id+"'");

            Rs.next();
            comboType.setSelectedItem(Rs.getString(2));
            comboSecteur.setSelectedItem(Rs.getString(3));
            txtSurface.setText(Rs.getString(4));
            txtChambres.setText(Rs.getString(5));
            txtSurTerrain.setText(Rs.getString(6));
            txtCE.setText(Rs.getString(7));  
            txtPlus.setText(Rs.getString(8));
            txtPrix.setText(Rs.getString(9));


        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"erreur de deplacement "+ex.getLocalizedMessage());
        }

    }//GEN-LAST:event_tblVentesMouseClicked

    private void btnSupprVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprVActionPerformed
        // TODO add your handling code here:
        
        try {
            
        String reference = null;
        reference = String.valueOf(tblVentes.getValueAt(tblVentes.getSelectedRow(), 0));
        
        
    if(JOptionPane.showConfirmDialog(null,"êtes vous sur de vouloir supprimer cette vente "
    ,"supprimer vente",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)
        

    if(reference.length() != 0) {
        stm.executeUpdate("Delete From vente where reference="+reference); afficher();
        
    }
    else {
        JOptionPane.showMessageDialog(null,"veuillez selectionner une vente !! "); 
        
    }
}   
catch(Exception e) 
{
    JOptionPane.showMessageDialog(null,"erreur suppr \n"+e.getMessage());
            
}    
  
        
        
    }//GEN-LAST:event_btnSupprVActionPerformed

    private void btnModifierVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierVActionPerformed
        // TODO add your handling code here:
        
        String reference = null;
        reference = String.valueOf(tblVentes.getValueAt(tblVentes.getSelectedRow(), 0));
        
        
try{
    if(JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
            JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
        
        stm.executeUpdate("UPDATE vente SET id_type='"+comboType.getSelectedIndex()+"',id_secteur='"+comboSecteur.getSelectedIndex()+
                "',surface='"+txtSurface.getText()+ "',chambres='"+txtChambres.getText()+"',surface_terrain='"+txtSurTerrain.getText()+
                "',classe_energetique='"+txtCE.getText()+"',les_plus='"+txtPlus.getText()+"',prix='"+txtPrix.getText()+"',img='"+txtImg.getText()+
                "' WHERE reference= "+reference);

        afficher();
               
    }
}     
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,"erreur modif ! "+e.getMessage());
    System.err.println(e);
}
                
        
    }//GEN-LAST:event_btnModifierVActionPerformed

    private void jFileVenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileVenteActionPerformed
        // TODO add your handling code here:
        
        txtImg.setText(jFileVente.getSelectedFile().getName());
        
    }//GEN-LAST:event_jFileVenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterV;
    private javax.swing.JButton btnModifierV;
    private javax.swing.JButton btnRetVentes;
    private javax.swing.JButton btnSupprV;
    private javax.swing.JComboBox<String> comboSecteur;
    public javax.swing.JComboBox<String> comboType;
    private javax.swing.JFileChooser jFileVente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentes;
    private javax.swing.JTextField txtCE;
    private javax.swing.JTextField txtChambres;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtPlus;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtSurTerrain;
    private javax.swing.JTextField txtSurface;
    // End of variables declaration//GEN-END:variables
}
